source 'http://rubygems.org'

gem 'rails', '3.0.0'

gem "jquery-rails"
gem 'mysql'
gem 'devise'
gem 'haml'
gem 'hpricot'
gem 'ruby_parser'
gem "rails3-generators", :group => :development

group :test do
  gem "shoulda"
  gem "rspec-rails", "2.0.0"
  gem "autotest"
  gem "factory_girl_rails"
end
